// <auto-generated />
using System;
using CarAllowedApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarAllowedApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251225060113_AddClass7")]
    partial class AddClass7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CarAllowedApi.Data.Garage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarProvince")
                        .HasColumnType("longtext");

                    b.Property<string>("CarRegistration")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CarStatusId")
                        .HasColumnType("longtext");

                    b.Property<string>("Carmodel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cartype")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("ImageFile")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Garages");
                });

            modelBuilder.Entity("CarAllowedApi.Data.ImageEmp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("EmpStatusId")
                        .HasColumnType("longtext");

                    b.Property<string>("Empposition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("ImageFile")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("ImageEmps");
                });

            modelBuilder.Entity("CarAllowedApi.Data.ImageFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("JobRequestCarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobRequestCarId");

                    b.ToTable("ImageFiles");
                });

            modelBuilder.Entity("CarAllowedApi.Data.JobImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("ImageFile")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int?>("JobRequestCarId")
                        .HasColumnType("int");

                    b.Property<int>("OpNoteDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobRequestCarId");

                    b.ToTable("JobImages");
                });

            modelBuilder.Entity("CarAllowedApi.Data.JobRequestCar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlongWith")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DateNow")
                        .HasColumnType("date");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("longtext");

                    b.Property<string>("Destination")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("EDateNow")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("ETimeNow")
                        .HasColumnType("time(0)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<string>("For")
                        .HasColumnType("longtext");

                    b.Property<int?>("GarageId")
                        .HasColumnType("int");

                    b.Property<int?>("ImageEmpId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("IssueTime")
                        .HasColumnType("time(0)");

                    b.Property<DateOnly>("JDDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("JDTime")
                        .HasColumnType("time(0)");

                    b.Property<int>("JobStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("LocationTime")
                        .HasColumnType("time(0)");

                    b.Property<string>("MileageBack")
                        .HasColumnType("longtext");

                    b.Property<string>("MileageOut")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int?>("NumOil")
                        .HasColumnType("int");

                    b.Property<int?>("NumPer")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .HasColumnType("longtext");

                    b.Property<string>("Ot")
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .HasColumnType("longtext");

                    b.Property<string>("Price")
                        .HasColumnType("longtext");

                    b.Property<string>("Requester")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("ReturnTime")
                        .HasColumnType("time(0)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(0)");

                    b.Property<DateOnly>("StatusDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StatusTime")
                        .HasColumnType("time(0)");

                    b.Property<string>("Tel")
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("TimeNow")
                        .HasColumnType("time(0)");

                    b.Property<DateOnly>("UpNDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("UpNTime")
                        .HasColumnType("time(0)");

                    b.HasKey("Id");

                    b.HasIndex("GarageId");

                    b.HasIndex("ImageEmpId");

                    b.HasIndex("JobStatusId");

                    b.ToTable("JobRequestCars");
                });

            modelBuilder.Entity("CarAllowedApi.Data.JobStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("JobStatuses");
                });

            modelBuilder.Entity("CarAllowedApi.Data.ImageFile", b =>
                {
                    b.HasOne("CarAllowedApi.Data.JobRequestCar", "JobRequestCar")
                        .WithMany()
                        .HasForeignKey("JobRequestCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRequestCar");
                });

            modelBuilder.Entity("CarAllowedApi.Data.JobImage", b =>
                {
                    b.HasOne("CarAllowedApi.Data.JobRequestCar", null)
                        .WithMany("ImageFiles")
                        .HasForeignKey("JobRequestCarId");
                });

            modelBuilder.Entity("CarAllowedApi.Data.JobRequestCar", b =>
                {
                    b.HasOne("CarAllowedApi.Data.Garage", "Garage")
                        .WithMany()
                        .HasForeignKey("GarageId");

                    b.HasOne("CarAllowedApi.Data.ImageEmp", "ImageEmp")
                        .WithMany("JobRequestCars")
                        .HasForeignKey("ImageEmpId");

                    b.HasOne("CarAllowedApi.Data.JobStatus", "JobStatus")
                        .WithMany("JobRequestCars")
                        .HasForeignKey("JobStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garage");

                    b.Navigation("ImageEmp");

                    b.Navigation("JobStatus");
                });

            modelBuilder.Entity("CarAllowedApi.Data.ImageEmp", b =>
                {
                    b.Navigation("JobRequestCars");
                });

            modelBuilder.Entity("CarAllowedApi.Data.JobRequestCar", b =>
                {
                    b.Navigation("ImageFiles");
                });

            modelBuilder.Entity("CarAllowedApi.Data.JobStatus", b =>
                {
                    b.Navigation("JobRequestCars");
                });
#pragma warning restore 612, 618
        }
    }
}
